---
- name: "5 - EDA: NetBox Playbooks"
  hosts: localhost
  become: false
  gather_facts: false

  collections:
    - ansible.controller

  vars:
    controller_host: localhost
    SANDBOX_ID: "{{ lookup('env', '_SANDBOX_ID') | default('SANDBOX_ID_NOT_FOUND', true) }}"
    controller_username: admin
    controller_password: ansible123!
    inventory_name: netbox-inventory
    credentials_name: cat8000v-credential


  tasks:
    - name: (EXECUTION) Create NetBox Playbooks Project from git
      ansible.controller.project:
        name: "NetBox Playbooks"
        organization: Default
        state: present
        scm_type: git
        scm_url: https://github.com/leogallego/cisco-netbox-playbooks.git
        validate_certs: false
        controller_username: admin
        controller_password: ansible123!

    - name: (EXECUTION) Create a Configure NTP Servers Job Template
      ansible.controller.job_template:
        name: "Configure NTP Servers"
        job_type: "run"
        organization: "Default"
        state: "present"
        inventory: "NetBox Dynamic Inventory"
        playbook: "configure_ntp.yml"
        project: "NetBox Playbooks"
        credential: "cat8000v-credential"
        validate_certs: false
        controller_username: admin
        controller_password: ansible123!

    - name: (EXECUTION) Create a Configure VLANS Job Template
      ansible.controller.job_template:
        name: "Configure VLANs"
        job_type: "run"
        organization: "Default"
        state: "present"
        inventory: "NetBox Dynamic Inventory"
        playbook: "configure_vlans.yml"
        project: "NetBox Playbooks"
        credential: "cat8000v-credential"
        validate_certs: false
        controller_username: admin
        controller_password: ansible123!

    - name: (EXECUTION) Create a Configure Login Banner Job Template
      ansible.controller.job_template:
        name: "Configure Login Banner"
        job_type: "run"
        organization: "Default"
        state: "present"
        inventory: "NetBox Dynamic Inventory"
        playbook: "configure_login_banner.yml"
        project: "NetBox Playbooks"
        credential: "cat8000v-credential"
        validate_certs: false
        controller_username: admin
        controller_password: ansible123!
